mealswap/edit/views.py
from flask import render_template, Blueprint, Response, redirect, url_for
from flask_login import login_required, current_user
from mealswap.controller.controls import get_element_by_id, Model, get_open_items_by_user, get_ratings_by_user, \
    get_saved_items_by_name, delete_meal_from_db
from mealswap.forms import SearchForm

blueprint = Blueprint('edit', __name__, static_folder='../static')


@blueprint.route('/edit_meals')
@login_required
def edit_meals() -> str:
    """Renders open meals available for editing.

    :return: rendered edit_meals template
    """
    items = get_open_items_by_user(current_user)
    return render_template('edit/edit_meals.html', user=current_user, items=items)


@blueprint.route('/edit_meals/delete/<item_id>')
@login_required
def delete_meal(item_id: str) -> Response:
    """Deletes open meal from database.

    :param item_id: id of the meal that is deleted
    :return: redirect to edit_meals after deleting item
    """
    item = get_element_by_id(Model.ITEM, item_id)
    delete_meal_from_db(item)
    return redirect(url_for('edit.edit_meals'))


@blueprint.route('/edit_ratings', methods=['GET', 'POST'])
@login_required
def edit_ratings() -> str or Response:
    """Renders ratings for meals with an option to change them.

    :return: rendered edit_ratings template OR
        redirect to edit_ratings_search after form validation
    """
    search_form = SearchForm()
    if search_form.validate_on_submit() and search_form.submitSearchForm.data:
        search_str = search_form.search.data
        return redirect(url_for('edit.edit_ratings_search', searched=search_str))

    return render_template('edit/edit_ratings.html', user=current_user, search_form=search_form)


@blueprint.route('/edit_ratings/<searched>')
@login_required
def edit_ratings_search(searched: str) -> str or Response:
    """Renders results for searching ratings to be edited.

    :param searched: string for saved items name query
    :return: rendered edit_ratings_search template
    """
    items_searched = get_saved_items_by_name(searched)
    assoc_items_rated = get_ratings_by_user(current_user)

    items = [(assoc.rating, assoc.item) for assoc in assoc_items_rated if assoc.item in items_searched]

    return render_template('edit/edit_ratings_search.html', user=current_user, items=items, searched=searched)

mealswap/rate/views.py
from flask import Blueprint, Response, redirect, url_for, render_template, request, flash, session
from flask_login import current_user, login_required
from mealswap.forms import SearchForm, DiscoverForm
from mealswap.controller.controls import Model, get_element_by_id, get_element_list_by_ids, set_rating, \
    get_saved_items, get_ratings_by_user, get_saved_items_by_name
from random import randrange

blueprint = Blueprint('rate', __name__, static_folder='../static')


@blueprint.route('/rate', methods=['GET', 'POST'])
@login_required
def rate() -> str or Response:
    """Renders instruction page for rating.

    :return: rendered rate template OR
        redirect to rate_search if searching for a particular item has been validated OR
        redirect to rate_discover if clicked on discover form
    """
    search_form = SearchForm()
    if search_form.validate_on_submit() and search_form.submitSearchForm.data:
        search_str = search_form.search.data
        return redirect(url_for('rate.rate_search', searched=search_str))

    discover_form = DiscoverForm()
    if discover_form.validate_on_submit() and discover_form.submitDiscoverForm.data:
        return redirect(url_for('rate.rate_discover'))

    return render_template('rate/rate.html', user=current_user, search_form=search_form, discover_form=discover_form)


@blueprint.route('/rate/<searched>')
@login_required
def rate_search(searched) -> str:
    """Renders results for searching meals to be rated.

    :param searched: string for saved items name query
    :return: rendered rate_search template
    """
    items_searched = get_saved_items_by_name(searched)
    assoc_items_rated = get_ratings_by_user(current_user)

    items_rated = [assoc.item for assoc in assoc_items_rated]
    items = [item for item in items_searched if item not in items_rated]

    return render_template('rate/rate_search.html', user=current_user, items=items, searched=searched)


@blueprint.route('/rate/discover')
@login_required
def rate_discover():
    """Renders a random meal to be rated.

    :return: rendered rate_discover template
    """
    items = session.get('rateable_items')  # get items if saved previously
    if items:
        items = get_element_list_by_ids(Model.ITEM, items)
    else:
        items = get_saved_items()
        items_rated = get_ratings_by_user(current_user)
        for assoc in items_rated:
            try:
                items.remove(assoc.item)
            except ValueError:
                continue
        rateable_items = [item.id for item in items]
        session['rateable_items'] = rateable_items  # saving for later

    if items:
        item = items[randrange(len(items))]
    else:
        item = None
    return render_template('rate/rate_discover.html', user=current_user, item=item)


@blueprint.route('/rate/commit')
@login_required
def rate_commit() -> Response:
    """Adds rating for the meal and returns the user to previous webpage.

    :return: redirect to edit_ratings if visited previously OR
        redirect to rate_search if visited previously OR
        redirect to rate_discover if visited previously
    """
    rating = request.args.get('rating')
    item_id = request.args.get('item_id')
    searched = request.args.get('searched')
    edit = request.args.get('edit')

    item = get_element_by_id(Model.ITEM, item_id)
    assoc = set_rating(item, current_user, rating)
    item_name = assoc.item.name

    if edit:
        flash(message=f"Rating for: '{item_name}' successfully updated!", category="success")
        return redirect(url_for('edit.edit_ratings'))

    if searched:
        return redirect(url_for('rate.rate_search', searched=searched))
    else:
        session['rateable_items'] = session['rateable_items'].remove(int(item_id))
        return redirect(url_for('rate.rate_discover'))

mealswap/user/views.py
from flask import render_template, flash, redirect, url_for, Response, Blueprint, abort
from flask_login import login_user, login_required, logout_user, current_user
from mealswap.extensions import login_manager, db
from mealswap.email import send_confirmation_msg
from mealswap.forms import RegisterForm, LoginForm, ChangePasswordForm, DeleteAccountForm, DietGoalPercentageForm, \
    DietGoalMacroForm
from .token import confirm_token, SignatureExpired, BadSignature
import datetime as dt
from ..controller.controls import add_user, get_user_by_email, get_element_by_id, Model, set_password, delete_account, \
    set_diet_goals

blueprint = Blueprint('user', __name__, static_folder='../static')


@blueprint.route('/register', methods=['GET', 'POST'])
def register() -> str or Response:
    """Renders the register page

    :return: rendered register template OR
        rendered confirm template if register form validated
    """
    form = RegisterForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        name = form.name.data

        add_user(email, password, name)
        send_confirmation_msg(form.email.data, form.name.data)

        return render_template('user/confirm.html', email=form.email.data, user=current_user)

    return render_template('user/register.html', form=form, user=current_user)


@blueprint.route("/login", methods=['GET', 'POST'])
def login() -> str or Response:
    """Renders the login page

    :return: rendered login page OR
        redirect to home page if form validated
    """
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        user = get_user_by_email(email)
        login_user(user, remember=form.remember.data)
        return redirect(url_for('public.home'))

    return render_template('user/login.html', form=form, user=current_user)


@blueprint.route('/logout')
@login_required
def logout() -> Response:
    """Logouts user, redirects to homepage

    :return: redirect to home page
    """
    logout_user()
    return redirect(url_for('public.home'))


@blueprint.route('/confirm/<token>')
def confirm_email(token: str) -> str or Response:
    """Renders email confirmation page

    :param token: token generated in the confirmation message during register
    :return: rendered confirm template
    """
    try:
        email = confirm_token(token)
    except SignatureExpired or BadSignature:
        flash('The confirmation link is invalid or it has expired', 'danger')
    else:
        user = get_user_by_email(email)
        if user:
            if user.confirmed:
                flash('Account has already been confirmed', 'success')
            else:
                user.confirmed = True
                user.confirmed_on = dt.datetime.now()
                db.session.commit()
                flash('You have successfully confirmed your account', 'success')
        else:
            return abort(404)
    return render_template('user/confirm.html', email=None, user=current_user)


@blueprint.route('/settings', methods=['GET', 'POST'])
@login_required
def settings() -> str or Response:
    """Renders settings page

    :return: rendered settings template OR
        redirect to settings if changed password, updated diet goals OR
        redirect to home page if user deleted account
    """

    change_password_form = ChangePasswordForm(current_user)
    if change_password_form.validate_on_submit():
        set_password(current_user, change_password_form.new_password.data)
        flash("Password changed.")
        return redirect(url_for('user.settings'))

    delete_form = DeleteAccountForm(current_user)
    if delete_form.validate_on_submit():
        logout_user()
        delete_account(current_user)
        return redirect(url_for('public.home'))

    diet_goal_percentage_form = DietGoalPercentageForm()
    if diet_goal_percentage_form.validate_on_submit():
        calories = diet_goal_percentage_form.calories.data
        protein_percent = diet_goal_percentage_form.protein.data
        carb_percent = diet_goal_percentage_form.carb.data
        fat_percent = diet_goal_percentage_form.fat.data
        set_diet_goals(current_user, calories, protein_percent, carb_percent, fat_percent, percentage=True)
        flash("Diet goals updated successfully.")
        return redirect(url_for('user.settings'))

    diet_goal_macro_form = DietGoalMacroForm()
    if diet_goal_macro_form.validate_on_submit():
        calories = diet_goal_macro_form.calories.data
        protein = diet_goal_macro_form.protein.data
        carb = diet_goal_macro_form.carb.data
        fat = diet_goal_macro_form.fat.data
        set_diet_goals(current_user, calories, protein, carb, fat, percentage=False)
        flash("Diet goals updated successfully.")
        return redirect(url_for('user.settings'))

    return render_template('user/settings.html', user=current_user, change_password_form=change_password_form,
                           delete_form=delete_form, diet_goal_percentage_form=diet_goal_percentage_form,
                           diet_goal_macro_form=diet_goal_macro_form)

mealswap/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="wiktor-jedski"/>
        <meta name="application-name" content="mealswap"/>
        <meta name="description" content="A web app for meal tracking, suggestion, replacement"/>

        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
            <!--Custom CSS-->
            <link rel="stylesheet" href="{{ url_for('.static', filename='css/styles.css') }}">
            <script src="https://kit.fontawesome.com/611ca9dd08.js" crossorigin="anonymous"></script>
        {% endblock %}

        <title>mealswap 🍲</title>
        {% endblock %}
    </head>
    <body>
        <section class="section-header" id="header__navbar">
            <nav class="navbar sticky-top navbar-dark navbar-expand-md" role="navigation">
                <a class="navbar-brand navbar-logo" href="{{ url_for('public.home') }}">mealswap 🍲</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse text-center justify-content-end" id="navbarNav">
                    {% if user.is_active %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link mx-3" href="{{ url_for('search.search') }}">Search</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                                Add
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{ url_for('add.add_product') }}">Product</a>
                                <a class="dropdown-item" href="{{ url_for('add.add_meal') }}">Meal</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                                Edit
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{ url_for('edit.edit_meals') }}">Meal</a>
                                <a class="dropdown-item" href="{{ url_for('edit.edit_ratings') }}">Rating</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-3" href="{{ url_for('rate.rate') }}">Rate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-3" href="{{ url_for('user.settings') }}">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-3" href="{{ url_for('user.logout') }}">Log Out</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link mx-3" href="{{ url_for('user.register') }}">Register</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link mx-3" href="{{ url_for('user.login') }}">Log In</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </nav>
        </section>
        <section class="section-flashes">
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% for message in messages %}
            {% if message[0] == 'success' %}
            <div class="alert alert-success alert-dismissible fade show mx-5" role="alert">
            {% elif message[0] == 'error' %}
            <div class="alert alert-error alert-dismissible fade show mx-5" role="alert">
            {% elif message[0] == 'warning' %}
            <div class="alert alert-warning alert-dismissible fade show mx-5" role="alert">
            {% else %}
            <div class="alert alert-dark alert-dismissible fade show mx-5" role="alert">
            {% endif %}
                {{ message[1] }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endwith %}
        </section>
        <!-- Page content -->
        {% block content %}{% endblock %}

        {% block footer %}
        <section class="section-footer">
            <div class="container-fluid">
                <div class="row text-center justify-content-center">
                    <div class="nav-item col-1">
                        <a href="{{ url_for('public.contact') }}" style="color: white">Contact & Info</a>
                    </div>
                    <div class="nav-item col-1">
                        <a href="{{ url_for('public.tos') }}" style="color: white">Terms of Service</a>
                    </div>
                    <div class="nav-item col-1">
                        <a href="{{ url_for('public.license_info') }}" style="color: white">License</a>
                    </div>
                </div>
                <div class="justify-content-center">
                    2022
                </div>
            </div>
        </section>
        {% endblock %}

        {% block scripts %}
            <!-- Optional JavaScript -->
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>