mealswap/add/views.py
from flask import Blueprint, Response, redirect, url_for, render_template, flash, abort, request
from flask_login import current_user, login_required
from mealswap.controller.controls import add_product_to_db, get_element_by_id, Model, add_meal_to_db, set_meal_recipe, \
    set_qty_in_meal, clear_meal, save_meal, get_products_by_name, add_product_to_meal, copy_meal, \
    delete_index_from_meal, get_saved_composed_items_by_name
from mealswap.forms import ProductForm, WeightMealForm, CompositeMealForm, LinkRecipeServingsForm, CopyMealForm, \
    SearchForm, EditForm, DeleteForm, SaveForm, ServingMealForm, QtyEaForm

blueprint = Blueprint('add', __name__, static_folder='../static')


@blueprint.route("/add_product", methods=['GET', 'POST'])
@login_required
def add_product() -> str or Response:
    """Renders form for adding products.

    :return: rendered 'add_product' template or redirect to add_product after adding product
    """
    form = ProductForm()
    if form.validate_on_submit() and form.submitProductForm.data:
        product = add_product_to_db(form.name.data, form.protein.data, form.carb.data, form.fat.data, current_user,
                                    weight_per_ea=form.weight_per_ea.data)

        flash(f'Product "{product.name}" successfully added!', category='success')
        return redirect(url_for('add.add_product'))
    return render_template('add/add_product.html', user=current_user, form=form)


@blueprint.route("/add_meal", methods=['GET', 'POST'])
@login_required
def add_meal() -> str or Response:
    """Renders form for adding meals.

    :return: rendered add_meal template OR
        redirect to add_meal if added empty meal OR
        redirect to compose_meal if added composed meal
    """
    weight_meal_form = WeightMealForm()
    if weight_meal_form.validate_on_submit() and weight_meal_form.submitWeightMealForm.data:
        has_weight = True
        qty = weight_meal_form.qty.data
        if qty:
            servings = 1
        else:
            servings = 0
        item = add_meal_to_db(weight_meal_form.name.data, weight_meal_form.protein.data, weight_meal_form.carb.data,
                              weight_meal_form.fat.data, current_user, has_weight, weight_meal_form.link.data,
                              weight_meal_form.recipe.data, saved=True, qty=qty, servings=servings)

        flash(f'Meal "{item.name}" successfully added!', category='success')
        return redirect(url_for('add.add_meal'))

    serving_meal_form = ServingMealForm()
    if serving_meal_form.validate_on_submit() and serving_meal_form.submitServingMealForm.data:
        has_weight = False
        item = add_meal_to_db(serving_meal_form.name.data, serving_meal_form.protein.data, serving_meal_form.carb.data,
                              serving_meal_form.fat.data, current_user, has_weight, serving_meal_form.link.data,
                              serving_meal_form.recipe.data, saved=True, qty=1, servings=1)

        flash(f'Meal "{item.name}" successfully added!', category='success')
        return redirect(url_for('add.add_meal'))

    composite_meal_form = CompositeMealForm()
    if composite_meal_form.validate_on_submit() and composite_meal_form.submitCompositeMealForm.data:
        has_weight = True
        item = add_meal_to_db(composite_meal_form.name.data, 0, 0, 0, current_user, has_weight,
                              composite_meal_form.link.data, composite_meal_form.recipe.data, saved=False,
                              qty=0, servings=1)

        return redirect(url_for('add.compose_meal', item_id=item.id))

    return render_template('add/add_meal.html', user=current_user, weight_meal_form=weight_meal_form,
                           serving_meal_form=serving_meal_form, composite_meal_form=composite_meal_form)


@blueprint.route("/compose_meal/<item_id>", methods=['GET', 'POST'])
@login_required
def compose_meal(item_id: str) -> str or Response:
    """Renders form for composing meals.

    :param item_id: id of the composed meal
    :return: rendered compose_meal template OR
        error 403 if user should not access the meal OR
        redirect to compose_meal if added additional data/edited qty/deleted all items OR
        redirect to compose_copy if searched for a meal to copy OR
        redirect to compose_search if searched for a product to add OR
        redirect to add_meal if the current meal has been saved
    """
    item = get_element_by_id(Model.ITEM, item_id)
    # prevent user from accessing a saved meal or another user's meal
    if item.saved or item.user != current_user:
        return abort(code=403)

    # update link and/or recipe
    link_recipe_form = LinkRecipeServingsForm()
    if link_recipe_form.validate_on_submit() and link_recipe_form.submitLinkRecipeForm.data:
        set_meal_recipe(item, link_recipe_form.link.data, link_recipe_form.recipe.data, link_recipe_form.servings.data)
        return redirect(url_for('add.compose_meal', item_id=item_id))
    link_recipe_form.link.data = item.link
    link_recipe_form.recipe.data = item.recipe
    link_recipe_form.servings.data = item.servings

    # create a copy of another meal
    copy_form = CopyMealForm()
    if copy_form.validate_on_submit() and copy_form.submitCopyMealForm.data:
        search_str = copy_form.search.data
        return redirect(url_for('add.compose_copy', searched=search_str, item_id=item_id))

    # search for products to add
    search_form = SearchForm()
    if search_form.validate_on_submit() and search_form.submitSearchForm.data:
        search_str = search_form.search.data
        return redirect(url_for('add.compose_search', searched=search_str, item_id=item.id))

    # edit qty for an item
    edit_form = EditForm()
    if edit_form.validate_on_submit():
        request_list = list(request.form)
        request_list.remove('qty')
        request_list.remove('csrf_token')
        index = request_list[0]
        new_qty = edit_form.qty.data

        assoc = get_element_by_id(Model.ITEM_PRODUCT, index)
        set_qty_in_meal(assoc, item, new_qty)
        return redirect(url_for('add.compose_meal', item_id=item_id))

    # delete all items
    delete_form = DeleteForm()
    if delete_form.validate_on_submit() and delete_form.submitDeleteForm.data:
        clear_meal(item)
        return redirect(url_for('add.compose_meal', item_id=item_id))

    # save meal and close for edits
    save_form = SaveForm()
    if save_form.validate_on_submit() and save_form.submitSaveForm.data:
        save_meal(item)
        return redirect(url_for('add.add_meal'))

    return render_template('add/compose_meal.html', edit_form=edit_form, copy_form=copy_form, save_form=save_form,
                           delete_form=delete_form, user=current_user, item=item, search_form=search_form,
                           link_recipe_form=link_recipe_form)


@blueprint.route("/compose_meal/<item_id>/<searched>", methods=['GET', 'POST'])
@login_required
def compose_search(item_id: str, searched: str) -> str or Response:
    """Renders search result for adding products to composed meals.

    :param item_id: id of the composed meal
    :param searched: name or part of the name of the product for search query
    :return: rendered compose_search template OR
        redirect to compose_meal if the product has been added
    """
    products = get_products_by_name(searched)
    form = QtyEaForm()
    if request.method == 'POST':
        request_list = list(request.form)
        request_list.remove('qty')
        request_list.remove('csrf_token')
        try:
            request_list.remove('ea')
        except ValueError:
            pass
        product_id = request_list[0]

        item = get_element_by_id(Model.ITEM, item_id)
        product = get_element_by_id(Model.PRODUCT, product_id)

        # anonymous form validation
        if not form.qty.data and not form.ea.data:
            flash("Either qty in grams or ea has to be filled.")
            return redirect(url_for('add.compose_search', item_id=item_id, searched=searched))
        elif form.qty.data and form.ea.data:
            flash("Please fill only one field - either qty in grams or ea.")
            return redirect(url_for('add.compose_search', item_id=item_id, searched=searched))
        elif form.qty.data:
            add_product_to_meal(item, product, form.qty.data)
        else:
            add_product_to_meal(item, product, form.ea.data*product.weight_per_ea)

        return redirect(url_for('add.compose_meal', item_id=item_id))
    return render_template('add/compose_search.html',
                           user=current_user, products=products, searched=searched, form=form)


@blueprint.route("/compose_meal/<item_id>/copy/<searched>", methods=['GET', 'POST'])
@login_required
def compose_copy(item_id: str, searched: str) -> str or Response:
    """Renders search results for copying existing meals.

    :param item_id: id of the composed meal
    :param searched: name or part of the name of the copied meal for search query
    :return: rendered compose_copy template OR
        redirect to compose_meal if a meal has been chosen to copy
    """
    items = get_saved_composed_items_by_name(searched)
    if request.method == 'POST':
        request_list = list(request.form)
        copy_item_id = request_list[0]

        copy_item = get_element_by_id(Model.ITEM, copy_item_id)
        item = get_element_by_id(Model.ITEM, item_id)
        copy_meal(item, copy_item)

        return redirect(url_for('add.compose_meal', item_id=item_id))

    return render_template('add/compose_copy.html', user=current_user, items=items, searched=searched)


@blueprint.route('/compose_meal/delete_pos')
@login_required
def delete_product_in_meal() -> Response:
    """Deletes the position from the meal.

    :return: redirect to compose_meal after deleting the product
    """
    assoc_id = request.args.get('assoc_id')
    item_id = request.args.get('item_id')

mealswap/controllers/add/__init__.py
from . import views

mealswap/templates/add/add_meal.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Add a new meal</h1>
    </div>
</section>
<section class="section-form">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item p-1 w-100">
                        <a class="btn btn-outline-success active w-100" id="pills-weight-tab" data-toggle="pill" href="#pills-weight"
                           role="tab" aria-controls="pill-empty" aria-selected="true">Add a meal with macronutrients per 100g</a>
                    </li>
                    <li class="nav-item p-1 w-100">
                        <a class="btn btn-outline-success w-100" id="pills-serving-tab" data-toggle="pill" href="#pills-serving"
                           role="tab" aria-controls="pill-serving" aria-selected="false">Add a meal with macronutrients per serving</a>
                    </li>
                    <li class="nav-item p-1 w-100">
                        <a class="btn btn-outline-success w-100" id="pills-compose-tab" data-toggle="pill" href="#pills-compose"
                           role="tab" aria-controls="pill-compose" aria-selected="false">Compose a meal out of products</a>
                    </li>
                </ul>
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-weight" role="tabpanel" aria-labelledby="pills-weight-tab">
                        {{ render_form(weight_meal_form) }}
                    </div>
                    <div class="tab-pane fade" id="pills-serving" role="tabpanel" aria-labelledby="pills-serving-tab">
                        {{ render_form(serving_meal_form) }}
                    </div>
                    <div class="tab-pane fade" id="pills-compose" role="tabpanel" aria-labelledby="pills-compose-tab">
                        {{ render_form(composite_meal_form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mealswap/templates/add/add_product.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Add a new product</h1>
    </div>
</section>
<section class="section-form">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                {{ render_form(form) }}
            </div>
        </div>
    </div>
</section>
{% endblock %}

mealswap/templates/add/compose_copy.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_field %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Copy meal: {{ searched }}</h1>
    </div>
</section>
{% if pagination.items %}
<div class="row justify-content-center">
    <div class="btn-group btn-group-sm" role="group" aria-label="Pagination buttons">
        {% if pagination.has_prev %}
            <a class="page-number btn btn-success" href="{{ url_for('add.compose_copy', page=pagination.prev_num) }}">
                {{ '<<<' }}
            </a>
        {% endif %}

        {% for number in pagination.iter_pages() %}
            {% if number %}
                {% if pagination.page != number %}
                    <a class="page-number btn btn-success" href="{{ url_for('add.compose_copy', page=number) }}">
                        {{ number }}
                    </a>
                {% else %}
                    <a class="btn btn-success disabled" aria-disabled="true">
                        {{ number }}
                    </a>
                {% endif %}
            {% else %}
                <a class="btn btn-success disabled" aria-disabled="true">
                    ...
                </a>
            {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
            <a class="page-number btn btn-success" href="{{ url_for('add.compose_copy', page=pagination.next_num) }}">
                {{ '>>>' }}
            </a>
        {% endif %}
    </div>
</div>
<section class="section-jumbo">
    {% for item in pagination.items %}
        <div class="row justify-content-center p-3">
            <div class="col-lg-6 col-md-12">
                <div class="jumbotron">
                    {% if item.link %}
                    <h1 class="display-4"><a href="{{ item.link }}" target="_blank">{{ item.name }}</a></h1>
                    {% else %}
                    <h1 class="display-4">{{ item.name }}</h1>
                    {% endif %}
                    <p class="lead">Calories per 100g: {{ item.calories|round(2) }}</p>
                    <p class="lead">Protein per 100g: {{ item.protein|round(2) }}</p>
                    <p class="lead">Carbs per 100g: {{ item.carb|round(2) }}</p>
                    <p class="lead">Fat per 100g: {{ item.fat|round(2) }}</p>
                    <hr class="my-4">
                    <form method="post">
                        <input type="submit" class="btn btn-success btn-block" name="{{ item.id }}" value="Copy">
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
</section>
<div class="row justify-content-center">
    <div class="btn-group btn-group-sm" role="group" aria-label="Pagination buttons">
        {% if pagination.has_prev %}
            <a class="page-number btn btn-success" href="{{ url_for('add.compose_copy', page=pagination.prev_num) }}">
                {{ '<<<' }}
            </a>
        {% endif %}

        {% for number in pagination.iter_pages() %}
            {% if number %}
                {% if pagination.page != number %}
                    <a class="page-number btn btn-success" href="{{ url_for('add.compose_copy', page=number) }}">
                        {{ number }}
                    </a>
                {% else %}
                    <a class="btn btn-success disabled" aria-disabled="true">
                        {{ number }}
                    </a>
                {% endif %}
            {% else %}
                <a class="btn btn-success disabled" aria-disabled="true">
                    ...
                </a>
            {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
            <a class="page-number btn btn-success" href="{{ url_for('add.compose_copy', page=pagination.next_num) }}">
                {{ '>>>' }}
            </a>
        {% endif %}
    </div>
</div>
{% else %}
<section class="section-diet">
    <div class="container-fluid text-center">
        <p>No search results for: {{ searched }}.</p>
    </div>
</section>
{% endif %}
{% endblock %}

mealswap/templates/add/compose_meal.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_field, render_form %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Compose meal: {{ item.name }}</h1>
        <p>Macros per 100g: {{ item.calories|round(2) }} kcal, {{ item.protein|round(2) }} g protein,
            {{ item.carb|round(2) }} g carbs, {{ item.fat|round(2) }} g fat</p>
    </div>
</section>

<section class="section-options">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                {{ link_recipe_form.csrf_token() }}
                {{ render_form(link_recipe_form) }}
            </div>
        </div>
    </div>
</section>

<section class="section-diet">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-4 text-center">
                <!-- ADD -->
                <button type="button" class="btn btn-success w-75" data-toggle="modal" data-target="#addModal">Add Item</button>
                <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
                    <div class="modal-dialog text-left">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="addModalLabel">Add Item</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container">
                                    <form method="post">
                                        {{ search_form.csrf_token() }}
                                        {{ render_field(search_form.search) }}
                                        <div class="row justify-content-around">
                                            <div class="col-6">
                                                {{ render_field(search_form.submitSearchForm) }}
                                            </div>
                                            <div class="col-6">
                                                <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 text-center">
                <!-- COPY -->
                <button type="button" class="btn btn-success w-75" data-toggle="modal" data-target="#copyModal">Copy Meal</button>
                <div class="modal fade" id="copyModal" tabindex="-1" aria-labelledby="copyModalLabel" aria-hidden="true">
                    <div class="modal-dialog text-left">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="copyModalLabel">Copy Meal</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container">
                                    <form method="post">
                                        {{ copy_form.csrf_token() }}
                                        {{ render_field(copy_form.search) }}
                                        <div class="row">
                                            <div class="col-6">
                                                {{ render_field(copy_form.submitCopyMealForm) }}
                                            </div>
                                            <div class="col-6">
                                                <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 text-center">
                <!-- DELETE -->
                <button type="button" class="btn btn-success w-75" data-toggle="modal" data-target="#deleteModal">Delete Items</button>
                <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog text-left">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete Items</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container">
                                    <form method="post">
                                        {{ delete_form.csrf_token() }}
                                        <p>Are you sure? All current data for this meal will be lost.</p>
                                        <div class="row">
                                            <div class="col-6">
                                                {{ render_field(delete_form.submitDeleteForm) }}
                                            </div>
                                            <div class="col-6">
                                                <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-lg-8 col-md-12">
                {% if item.products %}
                <div class="row font-weight-bold">
                    <div class="col-4">
                        Name/Calories/Weight
                    </div>
                    <div class="col-2">
                        Protein
                    </div>
                    <div class="col-2">
                        Carbs
                    </div>
                    <div class="col-2">
                        Fat
                    </div>
                </div>
                <hr>
                {% for a in item.products %}
                <div class="row">
                    <div class="col-10 small-heading">
                        {{ a.product.name }}: {{ (a.product.calories * a.qty / 100)|round(2) }} kcal
                    </div>
                    <div class="col-2">
                        <button type="button" class="btn btn-primary btn-sm btn-block" data-toggle="modal" data-target="#Modal{{ a.id }}">
                            Edit
                        </button>
                        <div class="modal fade" id="Modal{{ a.id }}" tabindex="-1" aria-labelledby="Modal{{ a.id }}Label" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="Modal{{ a.id }}Label">Edit qty for: {{ a.product.name }}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container">
                                            <form method="post">
                                                {{ edit_form.csrf_token() }}
                                                {{ render_field(edit_form.qty) }}
                                                <div class="row">
                                                    <div class="col-6">
                                                        <input type="submit" class="btn btn-success float-left" value="Edit" name="{{ a.id }}">
                                                    </div>
                                                    <div class="col-6">
                                                        <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col-4">
                        {{ a.qty|round(2) }} g
                    </div>
                    <div class="col-2">
                        {{ (a.product.protein * a.qty / 100)|round(2) }}
                    </div>
                    <div class="col-2">
                        {{ (a.product.carb * a.qty / 100)|round(2) }}
                    </div>
                    <div class="col-2">
                        {{ (a.product.fat * a.qty / 100)|round(2) }}
                    </div>
                    <div class="col-2">
                        <a href="{{ url_for('add.delete_product_in_meal', item_id=item.id, assoc_id=a.id) }}" class="btn btn-danger btn-sm btn-block">Delete</a>
                    </div>
                </div>
                <hr>
                {% endfor %}
                <div class="row py-2 justify-content-center">
                    <button type="button" class="btn btn-success w-75" data-toggle="modal" data-target="#saveModal">Save Meal</button>
                    <div class="modal fade" id="saveModal" tabindex="-1" aria-labelledby="saveModalLabel" aria-hidden="true">
                        <div class="modal-dialog text-left">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="saveModalLabel">Save Meal</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="container">
                                        <form method="post">
                                            {{ save_form.csrf_token() }}
                                            <p>Are you sure? This meal will be closed for editing, and you will be able to add it to diet.</p>
                                            <div class="row justify-content-around">
                                                <div class="col-6">
                                                    {{ render_field(save_form.submitSaveForm) }}
                                                </div>
                                                <div class="col-6">
                                                    <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="text-center">
                    No products yet. Maybe you want to add something?
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}