mealswap/controllers/edit/__init__.py
from . import views

mealswap/controllers/edit/views.py
from flask import render_template, Blueprint, Response, redirect, url_for, request
from flask_login import login_required, current_user
from mealswap.controllers.controls import get_element_by_id, Model, get_open_items_by_user, get_ratings_by_user, \
    get_saved_items_by_name, delete_meal_from_db
from mealswap.controllers.forms import SearchForm
from mealswap.controllers.search.helpers import paginate_list

blueprint = Blueprint('edit', __name__, static_folder='../static')


@blueprint.route('/edit_meals')
@login_required
def edit_meals() -> str:
    """Renders open meals available for editing.

    :return: rendered edit_meals template
    """
    page = request.args.get('page', 1, type=int)
    per_page = 5
    items = get_open_items_by_user(current_user, pagination=True, page=page, per_page=per_page)
    return render_template('edit/edit_meals.html', user=current_user, pagination=items)


@blueprint.route('/edit_meals/delete/<item_id>')
@login_required
def delete_meal(item_id: str) -> Response:
    """Deletes open meal from database.

    :param item_id: id of the meal that is deleted
    :return: redirect to edit_meals after deleting item
    """
    item = get_element_by_id(Model.ITEM, item_id)
    delete_meal_from_db(item)
    return redirect(url_for('edit.edit_meals'))


@blueprint.route('/edit_ratings', methods=['GET', 'POST'])
@login_required
def edit_ratings() -> str or Response:
    """Renders ratings for meals with an option to change them.

    :return: rendered edit_ratings template OR
        redirect to edit_ratings_search after form validation
    """
    search_form = SearchForm()
    if search_form.validate_on_submit() and search_form.submitSearchForm.data:
        search_str = search_form.search.data
        return redirect(url_for('edit.edit_ratings_search', searched=search_str))

    return render_template('edit/edit_ratings.html', user=current_user, search_form=search_form)


@blueprint.route('/edit_ratings/<searched>')
@login_required
def edit_ratings_search(searched: str) -> str or Response:
    """Renders results for searching ratings to be edited.

    :param searched: string for saved items name query
    :return: rendered edit_ratings_search template
    """
    page = request.args.get('page', 1, type=int)
    per_page = 5
    items_searched = get_saved_items_by_name(searched)
    assoc_items_rated = get_ratings_by_user(current_user)

    items = [(assoc.rating, assoc.item) for assoc in assoc_items_rated if assoc.item in items_searched]
    pagination = paginate_list(items, page, per_page)

    return render_template('edit/edit_ratings_search.html', user=current_user, pagination=pagination, searched=searched)

mealswap/edit/views.py
from flask import render_template, Blueprint, Response, redirect, url_for
from flask_login import login_required, current_user
from mealswap.controller.controls import get_element_by_id, Model, get_open_items_by_user, get_ratings_by_user, \
    get_saved_items_by_name, delete_meal_from_db
from mealswap.forms import SearchForm

blueprint = Blueprint('edit', __name__, static_folder='../static')


@blueprint.route('/edit_meals')
@login_required
def edit_meals() -> str:
    """Renders open meals available for editing.

    :return: rendered edit_meals template
    """
    items = get_open_items_by_user(current_user)
    return render_template('edit/edit_meals.html', user=current_user, items=items)


@blueprint.route('/edit_meals/delete/<item_id>')
@login_required
def delete_meal(item_id: str) -> Response:
    """Deletes open meal from database.

    :param item_id: id of the meal that is deleted
    :return: redirect to edit_meals after deleting item
    """
    item = get_element_by_id(Model.ITEM, item_id)
    delete_meal_from_db(item)
    return redirect(url_for('edit.edit_meals'))


@blueprint.route('/edit_ratings', methods=['GET', 'POST'])
@login_required
def edit_ratings() -> str or Response:
    """Renders ratings for meals with an option to change them.

    :return: rendered edit_ratings template OR
        redirect to edit_ratings_search after form validation
    """
    search_form = SearchForm()
    if search_form.validate_on_submit() and search_form.submitSearchForm.data:
        search_str = search_form.search.data
        return redirect(url_for('edit.edit_ratings_search', searched=search_str))

    return render_template('edit/edit_ratings.html', user=current_user, search_form=search_form)


@blueprint.route('/edit_ratings/<searched>')
@login_required
def edit_ratings_search(searched: str) -> str or Response:
    """Renders results for searching ratings to be edited.

    :param searched: string for saved items name query
    :return: rendered edit_ratings_search template
    """
    items_searched = get_saved_items_by_name(searched)
    assoc_items_rated = get_ratings_by_user(current_user)

    items = [(assoc.rating, assoc.item) for assoc in assoc_items_rated if assoc.item in items_searched]

    return render_template('edit/edit_ratings_search.html', user=current_user, items=items, searched=searched)

mealswap/rate/views.py
from flask import Blueprint, Response, redirect, url_for, render_template, request, flash, session
from flask_login import current_user, login_required
from mealswap.forms import SearchForm, DiscoverForm
from mealswap.controller.controls import Model, get_element_by_id, get_element_list_by_ids, set_rating, \
    get_saved_items, get_ratings_by_user, get_saved_items_by_name
from random import randrange

blueprint = Blueprint('rate', __name__, static_folder='../static')


@blueprint.route('/rate', methods=['GET', 'POST'])
@login_required
def rate() -> str or Response:
    """Renders instruction page for rating.

    :return: rendered rate template OR
        redirect to rate_search if searching for a particular item has been validated OR
        redirect to rate_discover if clicked on discover form
    """
    search_form = SearchForm()
    if search_form.validate_on_submit() and search_form.submitSearchForm.data:
        search_str = search_form.search.data
        return redirect(url_for('rate.rate_search', searched=search_str))

    discover_form = DiscoverForm()
    if discover_form.validate_on_submit() and discover_form.submitDiscoverForm.data:
        return redirect(url_for('rate.rate_discover'))

    return render_template('rate/rate.html', user=current_user, search_form=search_form, discover_form=discover_form)


@blueprint.route('/rate/<searched>')
@login_required
def rate_search(searched) -> str:
    """Renders results for searching meals to be rated.

    :param searched: string for saved items name query
    :return: rendered rate_search template
    """
    items_searched = get_saved_items_by_name(searched)
    assoc_items_rated = get_ratings_by_user(current_user)

    items_rated = [assoc.item for assoc in assoc_items_rated]
    items = [item for item in items_searched if item not in items_rated]

    return render_template('rate/rate_search.html', user=current_user, items=items, searched=searched)


@blueprint.route('/rate/discover')
@login_required
def rate_discover():
    """Renders a random meal to be rated.

    :return: rendered rate_discover template
    """
    items = session.get('rateable_items')  # get items if saved previously
    if items:
        items = get_element_list_by_ids(Model.ITEM, items)
    else:
        items = get_saved_items()
        items_rated = get_ratings_by_user(current_user)
        for assoc in items_rated:
            try:
                items.remove(assoc.item)
            except ValueError:
                continue
        rateable_items = [item.id for item in items]
        session['rateable_items'] = rateable_items  # saving for later

    if items:
        item = items[randrange(len(items))]
    else:
        item = None
    return render_template('rate/rate_discover.html', user=current_user, item=item)


@blueprint.route('/rate/commit')
@login_required
def rate_commit() -> Response:
    """Adds rating for the meal and returns the user to previous webpage.

    :return: redirect to edit_ratings if visited previously OR
        redirect to rate_search if visited previously OR
        redirect to rate_discover if visited previously
    """
    rating = request.args.get('rating')
    item_id = request.args.get('item_id')
    searched = request.args.get('searched')
    edit = request.args.get('edit')

    item = get_element_by_id(Model.ITEM, item_id)
    assoc = set_rating(item, current_user, rating)
    item_name = assoc.item.name

    if edit:
        flash(message=f"Rating for: '{item_name}' successfully updated!", category="success")
        return redirect(url_for('edit.edit_ratings'))

    if searched:
        return redirect(url_for('rate.rate_search', searched=searched))
    else:
        session['rateable_items'] = session['rateable_items'].remove(int(item_id))
        return redirect(url_for('rate.rate_discover'))

mealswap/templates/edit/edit_meals.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_field %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Your open meals</h1>
    </div>
</section>
{% if pagination.items %}
<div class="row justify-content-center">
    <div class="btn-group btn-group-sm" role="group" aria-label="Pagination buttons">
        {% if pagination.has_prev %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_meals', page=pagination.prev_num) }}">
                {{ '<<<' }}
            </a>
        {% endif %}

        {% for number in pagination.iter_pages() %}
            {% if number %}
                {% if pagination.page != number %}
                    <a class="page-number btn btn-success" href="{{ url_for('edit.edit_meals', page=number) }}">
                        {{ number }}
                    </a>
                {% else %}
                    <a class="btn btn-success disabled" aria-disabled="true">
                        {{ number }}
                    </a>
                {% endif %}
            {% else %}
                <a class="btn btn-success disabled" aria-disabled="true">
                    ...
                </a>
            {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_meals', page=pagination.next_num) }}">
                {{ '>>>' }}
            </a>
        {% endif %}
    </div>
</div>
<section class="section-jumbo">
    {% for item in pagination.items %}
        <div class="row justify-content-center p-3">
            <div class="col-lg-6 col-md-12">
                <div class="jumbotron">
                    {% if item.link %}
                    <h1 class="display-4"><a href="{{ item.link }}" target="_blank">{{ item.name }}</a></h1>
                    {% else %}
                    <h1 class="display-4">{{ item.name }}</h1>
                    {% endif %}
                    <p class="lead">Calories per 100g: {{ item.calories|round(2) }}</p>
                    <p class="lead">Protein per 100g: {{ item.protein|round(2) }}</p>
                    <p class="lead">Carbs per 100g: {{ item.carb|round(2) }}</p>
                    <p class="lead">Fat per 100g: {{ item.fat|round(2) }}</p>
                    <hr class="my-4">
                    {% if item.recipe %}
                    <p>{{ item.recipe }}</p>
                    {% endif %}
                    <div class="row">
                        <div class="col-6">
                            <a href="{{ url_for('add.compose_meal', item_id=item.id) }}" class="btn btn-success btn-block">Edit</a>
                        </div>
                        <div class="col-6 ">
                            <a href="{{ url_for('edit.delete_meal', item_id=item.id) }}" class="btn btn-danger btn-block float-right">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</section>
<div class="row justify-content-center">
    <div class="btn-group btn-group-sm" role="group" aria-label="Pagination buttons">
        {% if pagination.has_prev %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_meals', page=pagination.prev_num) }}">
                {{ '<<<' }}
            </a>
        {% endif %}

        {% for number in pagination.iter_pages() %}
            {% if number %}
                {% if pagination.page != number %}
                    <a class="page-number btn btn-success" href="{{ url_for('edit.edit_meals', page=number) }}">
                        {{ number }}
                    </a>
                {% else %}
                    <a class="btn btn-success disabled" aria-disabled="true">
                        {{ number }}
                    </a>
                {% endif %}
            {% else %}
                <a class="btn btn-success disabled" aria-disabled="true">
                    ...
                </a>
            {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_meals', page=pagination.next_num) }}">
                {{ '>>>' }}
            </a>
        {% endif %}
    </div>
</div>
{% else %}
<section class="section-diet">
    <div class="container-fluid text-center">
        <p>No open meals available.</p>
    </div>
</section>
{% endif %}
{% endblock %}

mealswap/templates/edit/edit_ratings.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Edit your ratings</h1>
    </div>
</section>
<section class="section-diet">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                {{ render_form(search_form) }}
            </div>
        </div>
    </div>
</section>
{% endblock %}

mealswap/templates/edit/edit_ratings_search.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_field %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Rating search for: {{ searched }}</h1>
    </div>
</section>
{% if pagination.items %}
<div class="row justify-content-center">
    <div class="btn-group btn-group-sm" role="group" aria-label="Pagination buttons">
        {% if pagination.has_prev %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_ratings_search', page=pagination.prev_num, searched=searched) }}">
                {{ '<<<' }}
            </a>
        {% endif %}

        {% for number in pagination.iter_pages() %}
            {% if number %}
                {% if pagination.page != number %}
                    <a class="page-number btn btn-success" href="{{ url_for('edit.edit_ratings_search', page=number, searched=searched) }}">
                        {{ number }}
                    </a>
                {% else %}
                    <a class="btn btn-success disabled" aria-disabled="true">
                        {{ number }}
                    </a>
                {% endif %}
            {% else %}
                <a class="btn btn-success disabled" aria-disabled="true">
                    ...
                </a>
            {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_ratings_search', page=pagination.next_num, searched=searched) }}">
                {{ '>>>' }}
            </a>
        {% endif %}
    </div>
</div>
<section class="section-jumbo">
    {% for item in pagination.items %}
        <div class="row justify-content-center p-3">
            <div class="col-lg-6 col-md-12">
                <div class="jumbotron">
                    {% if item[1].link %}
                    <h1 class="display-4"><a href="{{ item[1].link }}" target="_blank">{{ item[1].name }}</a></h1>
                    {% else %}
                    <h1 class="display-4">{{ item[1].name }}</h1>
                    {% endif %}
                    {% if item[1].has_weight %}
                    <p class="lead">Calories per 100g: {{ item[1].calories|round(2) }}</p>
                    <p class="lead">Protein per 100g: {{ item[1].protein|round(2) }}</p>
                    <p class="lead">Carbs per 100g: {{ item[1].carb|round(2) }}</p>
                    <p class="lead">Fat per 100g: {{ item[1].fat|round(2) }}</p>
                    {% else %}
                    <p class="lead">Calories per ea: {{ item[1].calories|round(2) }}</p>
                    <p class="lead">Protein per ea: {{ item[1].protein|round(2) }}</p>
                    <p class="lead">Carbs per ea: {{ item[1].carb|round(2) }}</p>
                    <p class="lead">Fat per ea: {{ item[1].fat|round(2) }}</p>
                    {% endif %}
                    <p class="lead">Current rating:
                        {% if item[0] == 3 %}
                        😋 Yum
                        {% elif item[0] == 2 %}
                        😑 Meh
                        {% else %}
                        🤮 Yuck
                        {% endif %}
                    </p>
                    <hr class="my-4">
                    {% if item[1].recipe %}
                    <p>{{ item[1].recipe }}</p>
                    {% endif %}
                    <div class="row justify-content-around text-center">
                        <div class="col-4">
                            <a href="{{ url_for('rate.rate_commit', rating=3, item_id=item[1].id, searched=searched, edit=1) }}" class="btn btn-light">😋<br>
                            Yum</a>
                        </div>
                        <div class="col-4">
                            <a href="{{ url_for('rate.rate_commit', rating=2, item_id=item[1].id, searched=searched, edit=1) }}" class="btn btn-light">😑<br>
                            Meh</a>
                        </div>
                        <div class="col-4">
                            <a href="{{ url_for('rate.rate_commit', rating=1, item_id=item[1].id, searched=searched, edit=1) }}" class="btn btn-light">🤮<br>
                            Yuck</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</section>
<div class="row justify-content-center">
    <div class="btn-group btn-group-sm" role="group" aria-label="Pagination buttons">
        {% if pagination.has_prev %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_ratings_search', page=pagination.prev_num, searched=searched) }}">
                {{ '<<<' }}
            </a>
        {% endif %}

        {% for number in pagination.iter_pages() %}
            {% if number %}
                {% if pagination.page != number %}
                    <a class="page-number btn btn-success" href="{{ url_for('edit.edit_ratings_search', page=number, searched=searched) }}">
                        {{ number }}
                    </a>
                {% else %}
                    <a class="btn btn-success disabled" aria-disabled="true">
                        {{ number }}
                    </a>
                {% endif %}
            {% else %}
                <a class="btn btn-success disabled" aria-disabled="true">
                    ...
                </a>
            {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
            <a class="page-number btn btn-success" href="{{ url_for('edit.edit_ratings_search', page=pagination.next_num, searched=searched) }}">
                {{ '>>>' }}
            </a>
        {% endif %}
    </div>
</div>
{% else %}
<section class="section-diet">
    <div class="container-fluid text-center">
        <p>No search results for: {{ searched }}.</p>
    </div>
</section>
{% endif %}
{% endblock %}