mealswap/controllers/user/__init__.py
from . import views

mealswap/controllers/user/views.py
from flask import render_template, flash, redirect, url_for, Response, Blueprint, abort
from flask_login import login_user, login_required, logout_user, current_user
from mealswap.extensions import db
from mealswap.email import send_confirmation_msg
from mealswap.controllers.forms import RegisterForm, LoginForm, ChangePasswordForm, DeleteAccountForm, DietGoalPercentageForm, \
    DietGoalMacroForm
from .token import confirm_token, SignatureExpired, BadSignature
import datetime as dt
from mealswap.controllers.controls import add_user, get_user_by_email, set_password, delete_account, \
    set_diet_goals, get_settings_by_user

blueprint = Blueprint('user', __name__, static_folder='../static')


@blueprint.route('/register', methods=['GET', 'POST'])
def register() -> str or Response:
    """Renders the register page

    :return: rendered register template OR
        rendered confirm template if register form validated
    """
    form = RegisterForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        name = form.name.data

        add_user(email, password, name)
        send_confirmation_msg(form.email.data, form.name.data)

        return render_template('user/confirm.html', email=form.email.data, user=current_user)

    return render_template('user/register.html', form=form, user=current_user)


@blueprint.route("/login", methods=['GET', 'POST'])
def login() -> str or Response:
    """Renders the login page

    :return: rendered login page OR
        redirect to home page if form validated
    """
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        user = get_user_by_email(email)
        login_user(user, remember=form.remember.data)
        return redirect(url_for('public.home'))

    return render_template('user/login.html', form=form, user=current_user)


@blueprint.route('/logout')
@login_required
def logout() -> Response:
    """Logouts user, redirects to homepage

    :return: redirect to home page
    """
    logout_user()
    return redirect(url_for('public.home'))


@blueprint.route('/confirm/<token>')
def confirm_email(token: str) -> str or Response:
    """Renders email confirmation page

    :param token: token generated in the confirmation message during register
    :return: rendered confirm template
    """
    try:
        email = confirm_token(token)
    except SignatureExpired or BadSignature:
        flash('The confirmation link is invalid or it has expired', 'error')
    else:
        user = get_user_by_email(email)
        if user:
            if user.confirmed:
                flash('Account has already been confirmed', 'success')
            else:
                user.confirmed = True
                user.confirmed_on = dt.datetime.now()
                db.session.commit()
                flash('You have successfully confirmed your account', 'success')
        else:
            return abort(404)
    return render_template('user/confirm.html', email=None, user=current_user)


@blueprint.route('/settings', methods=['GET', 'POST'])
@login_required
def settings() -> str or Response:
    """Renders settings page

    :return: rendered settings template OR
        redirect to settings if changed password, updated diet goals OR
        redirect to home page if user deleted account
    """

    current_settings = get_settings_by_user(current_user)

    change_password_form = ChangePasswordForm(current_user)
    if change_password_form.validate_on_submit():
        set_password(current_user, change_password_form.new_password.data)
        flash("Password changed.", category='success')
        return redirect(url_for('user.settings'))

    delete_form = DeleteAccountForm(current_user)
    if delete_form.validate_on_submit():
        logout_user()
        delete_account(current_user)
        return redirect(url_for('public.home'))

    diet_goal_percentage_form = DietGoalPercentageForm()
    if diet_goal_percentage_form.validate_on_submit():
        calories = diet_goal_percentage_form.calories.data
        protein_percent = diet_goal_percentage_form.protein.data
        carb_percent = diet_goal_percentage_form.carb.data
        fat_percent = diet_goal_percentage_form.fat.data
        set_diet_goals(current_user, calories, protein_percent, carb_percent, fat_percent, percentage=True)
        flash("Diet goals updated successfully.", category='success')
        return redirect(url_for('user.settings'))

    diet_goal_macro_form = DietGoalMacroForm()
    if diet_goal_macro_form.validate_on_submit():
        calories = diet_goal_macro_form.calories.data
        protein = diet_goal_macro_form.protein.data
        carb = diet_goal_macro_form.carb.data
        fat = diet_goal_macro_form.fat.data
        set_diet_goals(current_user, calories, protein, carb, fat, percentage=False)
        flash("Diet goals updated successfully.", category='success')
        return redirect(url_for('user.settings'))
    # populate the form if data exists
    if current_settings.calories_goal:
        diet_goal_macro_form.calories.data = current_settings.calories_goal
    if current_settings.protein_goal:
        diet_goal_macro_form.protein.data = current_settings.protein_goal
    if current_settings.carb_goal:
        diet_goal_macro_form.carb.data = current_settings.carb_goal
    if current_settings.fat_goal:
        diet_goal_macro_form.fat.data = current_settings.fat_goal

    return render_template('user/settings.html', user=current_user, change_password_form=change_password_form,
                           delete_form=delete_form, diet_goal_percentage_form=diet_goal_percentage_form,
                           diet_goal_macro_form=diet_goal_macro_form)

mealswap/diet/views.py
from flask import Blueprint, redirect, url_for, request, render_template, Response, flash
from flask_login import login_required, current_user
from mealswap.diet.helpers import get_calendar
from mealswap.controller.controls import Model, get_element_by_id, get_diet_by_date, add_diet, \
    delete_diet, edit_item_qty_in_diet, add_item_to_diet, get_saved_items_by_name, copy_diet, \
    delete_item_from_diet
from mealswap.forms import DateForm, SearchForm, DeleteForm, EditForm, QtyEaForm, EaEditForm

blueprint = Blueprint('diet', __name__, static_folder='../static')


@blueprint.route("/calendar", methods=['GET', 'POST'])
@login_required
def calendar() -> str or Response:
    """Starting page for looking up diet

    :return: rendered home page template OR
        redirect to chosen date
    """
    date_form = DateForm()
    if date_form.validate_on_submit():
        date = date_form.date.data
        return redirect(url_for('diet.day', date=date))

    title, table_rows = get_calendar()

    return render_template('diet/calendar.html', user=current_user, form=date_form, title=title, table_rows=table_rows)


@blueprint.route('/day/<date>', methods=['GET', 'POST'])
@login_required
def day(date: str) -> str or Response:
    """Renders the diet for the day

    :param date: date of the day for which user edits diet information
    :return: rendered day template OR
        redirect to the day if copied another diet, deleted diet, edited diet position OR
        redirect to search if searched for an item to add
    """
    diet = get_diet_by_date(date)
    total = {'calories': 0, 'protein': 0, 'carbs': 0, 'fat': 0}

    if diet:
        for a in diet.items:
            if a.item.has_weight:
                total['calories'] += a.item.calories * a.qty / 100
                total['protein'] += a.item.protein * a.qty / 100
                total['carbs'] += a.item.carb * a.qty / 100
                total['fat'] += a.item.fat * a.qty / 100
            else:
                total['calories'] += a.item.calories * a.qty
                total['protein'] += a.item.protein * a.qty
                total['carbs'] += a.item.carb * a.qty
                total['fat'] += a.item.fat * a.qty

    copy_form = DateForm()
    if copy_form.validate_on_submit():
        copy_date = copy_form.date.data
        copied = get_diet_by_date(copy_date)
        if copied:
            if diet is None:
                diet = add_diet(user=current_user, date=date)
            copy_diet(diet, copied)
            return redirect(url_for('diet.day', date=date))

    search_form = SearchForm()
    if search_form.validate_on_submit():
        search_str = search_form.search.data
        return redirect(url_for('diet.diet_search', searched=search_str, date=date))

    delete_form = DeleteForm()
    if delete_form.validate_on_submit():
        delete_diet(diet)
        return redirect(url_for('diet.day', date=date))

    edit_form = EditForm()
    if edit_form.validate_on_submit():
        request_list = list(request.form)
        request_list.remove('qty')
        request_list.remove('csrf_token')
        assoc_id = request_list[0]

        assoc = get_element_by_id(Model.DIET_ITEM, assoc_id)
        edit_item_qty_in_diet(assoc, new_qty=edit_form.qty.data)
        
        return redirect(url_for('diet.day', date=date))

    ea_edit_form = EaEditForm()
    if ea_edit_form.validate_on_submit():
        request_list = list(request.form)
        request_list.remove('qty')
        request_list.remove('csrf_token')
        assoc_id = request_list[0]

        assoc = get_element_by_id(Model.DIET_ITEM, assoc_id)
        edit_item_qty_in_diet(assoc, new_qty=ea_edit_form.qty.data)

        return redirect(url_for('diet.day', date=date))

    return render_template('diet/day.html',
                           user=current_user, date=date, diet=diet, total=total, edit_form=edit_form,
                           date_form=copy_form, search_form=search_form, delete_form=delete_form,
                           ea_edit_form=ea_edit_form)


@blueprint.route('/day/delete')
@login_required
def delete_item_in_day() -> Response:
    """Deletes the position from the diet for the date.

    :return: redirect to the diet after deleting position
    """
    assoc_id = request.args.get('assoc_id')
    diet_id = request.args.get('diet_id')
    date = request.args.get('date')

    assoc = get_element_by_id(Model.DIET_ITEM, assoc_id)
    diet = get_element_by_id(Model.DAY, diet_id)
    delete_item_from_diet(assoc, diet)
    
    if not diet.items:
        delete_diet(diet)

    return redirect(url_for('diet.day', date=date))


@blueprint.route("/day/<date>/add/<searched>", methods=['GET', 'POST'])
@login_required
def diet_search(searched, date) -> str or Response:
    """Renders item search results for searched string.

    :param searched: string for item name query
    :param date: date of the diet that is edited
    :return: rendered search template OR
        redirect to search if form for adding meals has not passed validation OR
        redirect to diet if item successfully added
    """
    items = get_saved_items_by_name(searched)
    form = QtyEaForm()
    if request.method == 'POST':
        request_list = list(request.form)
        request_list.remove('csrf_token')
        try:
            request_list.remove('qty')
            qty = form.qty.data
        except ValueError:
            qty = None
        try:
            request_list.remove('ea')
            ea = form.ea.data
        except ValueError:
            ea = None
        item_id = request_list[0]
        
        item = get_element_by_id(Model.ITEM, item_id)
        diet = get_diet_by_date(date)

        # anonymous form validation
        if qty is None and ea is None:
            flash("Either qty in grams or ea has to be filled.")
            return redirect(url_for('diet.diet_search', searched=searched, date=date))
        if qty and ea:
            flash("Please fill only one field - either qty in grams or ea.")
            return redirect(url_for('diet.diet_search', searched=searched, date=date))

        if diet is None:
            diet = add_diet(user=current_user, date=date)

        add_item_to_diet(item, qty, ea, diet)
        
        return redirect(url_for('diet.day', date=date))
    return render_template('diet/diet_search.html',
                           user=current_user, items=items, date=date, searched=searched, form=form)

mealswap/user/views.py
from flask import render_template, flash, redirect, url_for, Response, Blueprint, abort
from flask_login import login_user, login_required, logout_user, current_user
from mealswap.extensions import login_manager, db
from mealswap.email import send_confirmation_msg
from mealswap.forms import RegisterForm, LoginForm, ChangePasswordForm, DeleteAccountForm, DietGoalPercentageForm, \
    DietGoalMacroForm
from .token import confirm_token, SignatureExpired, BadSignature
import datetime as dt
from ..controller.controls import add_user, get_user_by_email, get_element_by_id, Model, set_password, delete_account, \
    set_diet_goals

blueprint = Blueprint('user', __name__, static_folder='../static')


@blueprint.route('/register', methods=['GET', 'POST'])
def register() -> str or Response:
    """Renders the register page

    :return: rendered register template OR
        rendered confirm template if register form validated
    """
    form = RegisterForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        name = form.name.data

        add_user(email, password, name)
        send_confirmation_msg(form.email.data, form.name.data)

        return render_template('user/confirm.html', email=form.email.data, user=current_user)

    return render_template('user/register.html', form=form, user=current_user)


@blueprint.route("/login", methods=['GET', 'POST'])
def login() -> str or Response:
    """Renders the login page

    :return: rendered login page OR
        redirect to home page if form validated
    """
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        user = get_user_by_email(email)
        login_user(user, remember=form.remember.data)
        return redirect(url_for('public.home'))

    return render_template('user/login.html', form=form, user=current_user)


@blueprint.route('/logout')
@login_required
def logout() -> Response:
    """Logouts user, redirects to homepage

    :return: redirect to home page
    """
    logout_user()
    return redirect(url_for('public.home'))


@blueprint.route('/confirm/<token>')
def confirm_email(token: str) -> str or Response:
    """Renders email confirmation page

    :param token: token generated in the confirmation message during register
    :return: rendered confirm template
    """
    try:
        email = confirm_token(token)
    except SignatureExpired or BadSignature:
        flash('The confirmation link is invalid or it has expired', 'danger')
    else:
        user = get_user_by_email(email)
        if user:
            if user.confirmed:
                flash('Account has already been confirmed', 'success')
            else:
                user.confirmed = True
                user.confirmed_on = dt.datetime.now()
                db.session.commit()
                flash('You have successfully confirmed your account', 'success')
        else:
            return abort(404)
    return render_template('user/confirm.html', email=None, user=current_user)


@blueprint.route('/settings', methods=['GET', 'POST'])
@login_required
def settings() -> str or Response:
    """Renders settings page

    :return: rendered settings template OR
        redirect to settings if changed password, updated diet goals OR
        redirect to home page if user deleted account
    """

    change_password_form = ChangePasswordForm(current_user)
    if change_password_form.validate_on_submit():
        set_password(current_user, change_password_form.new_password.data)
        flash("Password changed.")
        return redirect(url_for('user.settings'))

    delete_form = DeleteAccountForm(current_user)
    if delete_form.validate_on_submit():
        logout_user()
        delete_account(current_user)
        return redirect(url_for('public.home'))

    diet_goal_percentage_form = DietGoalPercentageForm()
    if diet_goal_percentage_form.validate_on_submit():
        calories = diet_goal_percentage_form.calories.data
        protein_percent = diet_goal_percentage_form.protein.data
        carb_percent = diet_goal_percentage_form.carb.data
        fat_percent = diet_goal_percentage_form.fat.data
        set_diet_goals(current_user, calories, protein_percent, carb_percent, fat_percent, percentage=True)
        flash("Diet goals updated successfully.")
        return redirect(url_for('user.settings'))

    diet_goal_macro_form = DietGoalMacroForm()
    if diet_goal_macro_form.validate_on_submit():
        calories = diet_goal_macro_form.calories.data
        protein = diet_goal_macro_form.protein.data
        carb = diet_goal_macro_form.carb.data
        fat = diet_goal_macro_form.fat.data
        set_diet_goals(current_user, calories, protein, carb, fat, percentage=False)
        flash("Diet goals updated successfully.")
        return redirect(url_for('user.settings'))

    return render_template('user/settings.html', user=current_user, change_password_form=change_password_form,
                           delete_form=delete_form, diet_goal_percentage_form=diet_goal_percentage_form,
                           diet_goal_macro_form=diet_goal_macro_form)

mealswap/templates/user/confirm.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Just a couple more steps...</h1>
    </div>
</section>
<section class="section-form">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12 text-center">
                <p>A confirmation link has been sent to your email at {{ email }}. Please follow the link to continue.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mealswap/templates/user/day.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_field, render_form %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Diet for: {{ date }}</h1>
        <p>Total: {{ total['calories']|round(2) }} kcal, {{ total['protein']|round(2) }} g protein,
            {{ total['carbs']|round(2) }} g carbs, {{ total['fat']|round(2) }} g fat</p>
        <p>Goal: Not yet implemented :(</p>
    </div>
</section>

<section class="section-diet">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-6 text-center">
                <!-- ADD -->
                <button type="button" class="btn btn-success w-75" data-toggle="modal" data-target="#addModal">Add Item</button>
                <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
                    <div class="modal-dialog text-left">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="addModalLabel">Add Item</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container">
                                    <form method="post">
                                        {{ search_form.csrf_token() }}
                                        {{ render_field(search_form.search) }}
                                        <div class="row justify-content-around">
                                            <div class="col-6">
                                                {{ render_field(search_form.submit) }}
                                            </div>
                                            <div class="col-6">
                                                <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <!-- COPY -->
                <button type="button" class="btn btn-success w-75" data-toggle="modal" data-target="#copyModal">Copy Day</button>
                <div class="modal fade" id="copyModal" tabindex="-1" aria-labelledby="copyModalLabel" aria-hidden="true">
                    <div class="modal-dialog text-left">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="copyModalLabel">Copy Day</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container">
                                    <form method="post">
                                        {{ date_form.csrf_token() }}
                                        {{ render_field(date_form.date) }}
                                        <div class="row">
                                            <div class="col-6">
                                                {{ render_field(date_form.submit) }}
                                            </div>
                                            <div class="col-6">
                                                <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <!-- DELETE -->
                <button type="button" class="btn btn-success w-75" data-toggle="modal" data-target="#deleteModal">Delete All</button>
                <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog text-left">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete All</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container">
                                    <form method="post">
                                        {{ delete_form.csrf_token() }}
                                        <p>Are you sure? All current data for this day will be lost.</p>
                                        {{ render_field(delete_form.confirm) }}
                                        <div class="row">
                                            <div class="col-6">
                                                {{ render_field(delete_form.submit) }}
                                            </div>
                                            <div class="col-6">
                                                <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-lg-8 col-md-12">
                {% if diet.items %}
                <div class="row font-weight-bold">
                    <div class="col-4">
                        Name/Calories/Weight
                    </div>
                    <div class="col-2">
                        Protein
                    </div>
                    <div class="col-2">
                        Carbs
                    </div>
                    <div class="col-2">
                        Fat
                    </div>
                </div>
                <hr>
                {% for a in diet.items %}
                <div class="row">
                    <div class="col-10 small-heading">
                        {{ a.item.name }}: {{ (a.item.calories * a.qty / 100 )|round(2)}} kcal
                    </div>
                    <div class="col-2">
                        <button type="button" class="btn btn-primary btn-sm btn-block" data-toggle="modal" data-target="#Modal{{ a.index }}">
                            Edit
                        </button>
                        <div class="modal fade" id="Modal{{ a.index }}" tabindex="-1" aria-labelledby="Modal{{ a.index }}Label" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="Modal{{ a.index }}Label">Edit qty for: {{ a.item.name }}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container">
                                            <form method="post">
                                                {{ edit_form.csrf_token() }}
                                                {{ render_field(edit_form.qty) }}
                                                <div class="row">
                                                    <div class="col-6">
                                                        <input type="submit" class="btn btn-success float-left" value="Edit" name="{{ a.index }}">
                                                    </div>
                                                    <div class="col-6">
                                                        <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col-4">
                        {{ (a.qty)|round(2) }} g
                    </div>
                    <div class="col-2">
                        {{ (a.item.protein * a.qty / 100)|round(2) }}
                    </div>
                    <div class="col-2">
                        {{ (a.item.carb * a.qty / 100)|round(2) }}
                    </div>
                    <div class="col-2">
                        {{ (a.item.fat * a.qty / 100)|round(2) }}
                    </div>
                    <div class="col-2">
                        <a href="{{ url_for('user.delete_item_in_day', index=a.index, diet_id=diet.id, date=date) }}" class="btn btn-danger btn-sm btn-block">Delete</a>
                    </div>
                </div>
                <hr>
                {% endfor %}
                {% else %}
                No items yet. Maybe you want to add something?
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

mealswap/templates/user/login.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Glad to see you back!</h1>
    </div>
</section>
<section class="section-form">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                {{ render_form(form) }}
                <p class="mt-3">Don't have an account? Register <a href="{{ url_for('user.register') }}">here.</a></p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mealswap/templates/user/register.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_field %}

{% block content %}
<section class="section-header">
    <div class="container-fluid">
        <h1 class="big-heading">Register - it's 100% free.</h1>
    </div>
</section>
<section class="section-form">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12">
                <form method="post">
                    {{ form.csrf_token() }}
                    {{ render_field(form.name) }}
                    {{ render_field(form.email) }}
                    {{ render_field(form.password) }}
                    {{ render_field(form.confirmation) }}
                    {{ render_field(form.submit) }}
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}